name: "Run tests"

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out repository, so the job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r tests/requirements.txt

      - name: Check order of imports
        uses: isort/isort-action@master
        with:
            configuration: "--check-only"

      - name: Lint with flake8
        run: |        
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --exit-zero --max-complexity=10 --max-line-length=80
